print("This file was created within RStudio")
print("And now it lives on GitHub")
install.packages(rtools)
install.packages("rmarkdown")
library(rmarkdown)
library(rtools)
install.packages(rtools)
install.packages("rtools")
install.packages("installr")
library(installr)
